/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=wrangler.jsonc --include-runtime=false` (hash: 655c1851499766c23445ddb2c29990e5)
interface __BaseEnv_Env {

}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface StagingEnv {}
	interface ProductionEnv {}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
